#!/bin/bash
usage() { echo "Usage: $0 [-i plugin_name] [-r plugin_name]" 1>&2; exit 1; }

while getopts ":i:r:lu" o; do
    case "${o}" in
        i)
            i=${OPTARG}
            ;;
        r)
            r=${OPTARG}
            ;;
        u)
            u=${OPTARG}
            echo "Updating plugins.."
            # git submodule update --remote --merge --recursive
            git submodule foreach git pull
            git add .
            git commit -m 'update plugins to latest version'
            exit
            ;;
        l)
            l=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))
echo $@
if [ -z "${i}" ] && [ -z "${r}" ]; then
    usage
fi

exit

if [ ! -z "${i}" ]; then
    name=${i}
    url=https://github.com/${i}.git
    git submodule add ${url} repos/${name}
    cd pack/base/start
    ln -s ../../../repos/${name} .
    git add .
    git commit -am "installed ${name} plugin"
    exit
fi

if [ ! -z "${r}" ]; then
    shortname=`echo $r | rev | cut -d'/' -f1 | rev`
    git rm pack/base/start/$shortname
    git submodule deinit -f repos/${r}
    git rm repos/${r}
    rm -rf .git/modules/repos/${r}
    git commit -m "uninstalled ${r} plugin"
fi


